// Generated by CoffeeScript 1.3.3
(function() {

  module.exports = function(Mf) {
    var cookieKiller, replacement;
    cookieKiller = function(req, res, next) {
      res.removeHeader("set-cookie");
      return next();
    };
    replacement = function(string, req, res) {
      var contentType;
      contentType = res.headers['content-type'] || '';
      if (contentType.search(/html/) >= 0) {
        return string.replace(/repositories/ig, "suppositories");
      } else {
        return false;
      }
    };
    return [cookieKiller, Mf.replace(replacement)];
  };

}).call(this);
