// Generated by CoffeeScript 1.3.3
(function() {

  module.exports = function(Mf) {
    return function(req, res, next) {
      req.headers['user-agent'] = "iPhone";
      return next();
    };
  };

}).call(this);
