// Generated by CoffeeScript 1.3.3
(function() {

  module.exports = function(Mf) {
    return function(req, res, next) {
      console.log("ftttt")
      req.headers['user-agent'] = "GoogleBot";
      return next();
    };
  };

}).call(this);
