// Generated by CoffeeScript 1.3.3
(function() {

  module.exports = function(Mf) {
    var replace, ua;
    ua = function(req, res, next) {
      req.headers['user-agent'] = "GoogleBotZ";
      res.on('headers', function(headers) {
        return headers['server'] = "Apache";
      });
      return next();
    };
    replace = function(string, req, res) {
      if (res.headers['content-type'].match('html')) {
        return string.replace(/Lucky/gi, 'Unlucky');
      } else {
        return false;
      }
    };
    return [ua, Mf.replace(replace)];
  };

}).call(this);
