// Generated by CoffeeScript 1.3.3
(function() {

  module.exports = function(Mf) {
    return function(req, res, next) {
      res.removeHeader('server');
      return next();
    };
  };

}).call(this);
